CREATE TABLE IF NOT EXISTS portal_overview (
	id INT AUTO_INCREMENT PRIMARY KEY,
	site_name VARCHAR(120) NOT NULL,
	farm_mode VARCHAR(64) NOT NULL,
	water_quality_score INT NOT NULL,
	active_alerts INT NOT NULL,
	online_devices INT NOT NULL,
	prediction_confidence INT NOT NULL,
	last_sync DATETIME NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS latest_metrics (
	id INT AUTO_INCREMENT PRIMARY KEY,
	metric_name VARCHAR(64) NOT NULL,
	metric_value DECIMAL(10,2) NOT NULL,
	metric_unit VARCHAR(32) NOT NULL,
	metric_status VARCHAR(32) NOT NULL,
	metric_trend VARCHAR(32) NOT NULL,
	display_order INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS alerts (
	id INT AUTO_INCREMENT PRIMARY KEY,
	severity VARCHAR(32) NOT NULL,
	title VARCHAR(120) NOT NULL,
	message TEXT NOT NULL,
	alert_time VARCHAR(16) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS devices (
	id INT AUTO_INCREMENT PRIMARY KEY,
	device_name VARCHAR(120) NOT NULL,
	device_type VARCHAR(64) NOT NULL,
	device_status VARCHAR(32) NOT NULL,
	location VARCHAR(120) NOT NULL,
	last_seen VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS predictions (
	id INT AUTO_INCREMENT PRIMARY KEY,
	model_name VARCHAR(120) NOT NULL,
	forecast_window VARCHAR(64) NOT NULL,
	prediction_result VARCHAR(255) NOT NULL,
	confidence VARCHAR(64) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quality_timeline (
	id INT AUTO_INCREMENT PRIMARY KEY,
	time_label VARCHAR(32) NOT NULL,
	quality_score INT NOT NULL,
	point_order INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(64) NOT NULL UNIQUE,
	display_name VARCHAR(120) NOT NULL,
	role VARCHAR(32) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS telemetry_samples (
	id INT AUTO_INCREMENT PRIMARY KEY,
	sampled_at DATETIME NOT NULL,
	pond_code VARCHAR(32) NOT NULL DEFAULT 'pond_01',
	temperature DECIMAL(10,2) NULL,
	ph DECIMAL(10,2) NULL,
	do_value DECIMAL(10,2) NULL,
	turbidity DECIMAL(10,2) NULL,
	water_level DECIMAL(10,2) NULL,
	ammonia_nitrogen DECIMAL(10,2) NULL,
	nitrite DECIMAL(10,2) NULL,
	salinity DECIMAL(10,2) NULL,
	alkalinity DECIMAL(10,2) NULL,
	alert_text VARCHAR(255) NOT NULL DEFAULT 'normal',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE KEY uniq_telemetry_pond_time (pond_code, sampled_at)
);

CREATE TABLE IF NOT EXISTS control_commands (
	id INT AUTO_INCREMENT PRIMARY KEY,
	device_name VARCHAR(120) NOT NULL,
	action_name VARCHAR(64) NOT NULL,
	operator_name VARCHAR(120) NOT NULL,
	command_status VARCHAR(32) NOT NULL DEFAULT 'queued',
	issued_at DATETIME NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS weather_snapshots (
	id INT AUTO_INCREMENT PRIMARY KEY,
	recorded_at DATETIME NOT NULL,
	air_temperature DECIMAL(10,2) NOT NULL,
	rainfall_mm DECIMAL(10,2) NOT NULL,
	humidity DECIMAL(10,2) NOT NULL,
	forecast_summary VARCHAR(255) NOT NULL,
	stress_risk VARCHAR(64) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS camera_feeds (
	id INT AUTO_INCREMENT PRIMARY KEY,
	camera_name VARCHAR(120) NOT NULL,
	location VARCHAR(120) NOT NULL,
	stream_status VARCHAR(32) NOT NULL,
	visibility_score INT NOT NULL,
	shrimp_activity_index DECIMAL(10,2) NOT NULL,
	last_frame_at DATETIME NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS medication_recommendations (
	id INT AUTO_INCREMENT PRIMARY KEY,
	recommendation_title VARCHAR(160) NOT NULL,
	recommendation_text TEXT NOT NULL,
	recommended_window VARCHAR(120) NOT NULL,
	risk_level VARCHAR(32) NOT NULL,
	status VARCHAR(32) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS custom_cards (
	id INT AUTO_INCREMENT PRIMARY KEY,
	card_title VARCHAR(120) NOT NULL,
	card_value VARCHAR(120) NOT NULL,
	card_note VARCHAR(255) NOT NULL,
	card_style VARCHAR(32) NOT NULL DEFAULT 'neutral',
	display_order INT NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS backup_snapshots (
	id INT AUTO_INCREMENT PRIMARY KEY,
	file_name VARCHAR(255) NOT NULL,
	file_path VARCHAR(255) NOT NULL,
	created_by VARCHAR(120) NOT NULL,
	backup_status VARCHAR(32) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_logs (
	id INT AUTO_INCREMENT PRIMARY KEY,
	log_level VARCHAR(32) NOT NULL,
	log_source VARCHAR(64) NOT NULL,
	message TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
